"""Add ScenePair and ChangeResult tables

Revision ID: c4a057658854
Revises: 995fa8c77e5c
Create Date: 2026-09-23 16:40:34.470070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a057658854'
down_revision: Union[str, Sequence[str], None] = '995fa8c77e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('before_scene_id', sa.Integer(), nullable=True),
    sa.Column('after_scene_id', sa.Integer(), nullable=True),
    sa.Column('coregistration_status', sa.String(), nullable=True),
    sa.Column('before_aligned_path', sa.String(), nullable=True),
    sa.Column('after_aligned_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['after_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['before_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_pairs_id'), 'scene_pairs', ['id'], unique=False)
    op.create_table('change_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_pair_id', sa.Integer(), nullable=True),
    sa.Column('mask_path', sa.String(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_pair_id'], ['scene_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_results_id'), 'change_results', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_change_results_id'), table_name='change_results')
    op.drop_table('change_results')
    op.drop_index(op.f('ix_scene_pairs_id'), table_name='scene_pairs')
    op.drop_table('scene_pairs')
    # ### end Alembic commands ###
