"""Add SAR columns to Scene

Revision ID: c732c44b8d7a
Revises: c4a057658854
Create Date: 2026-09-23 16:48:32.268588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c732c44b8d7a'
down_revision: Union[str, Sequence[str], None] = 'c4a057658854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('scenes', sa.Column('sensor_type', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('sar_polarization', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('sar_acquisition_mode', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('sar_incidence_angle', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'sar_incidence_angle')
    op.drop_column('scenes', 'sar_acquisition_mode')
    op.drop_column('scenes', 'sar_polarization')
    op.drop_column('scenes', 'sensor_type')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
