'use client';
import { useState } from 'react';
import QueryBox from '@/components/QueryBox';
import MapViewer, { MapLayerConfig } from '@/components/MapViewer';
import ImageUploader from '@/components/ImageUploader';
import AnalysisStatus from '@/components/AnalysisStatus';
import ResultPanel from '@/components/ResultPanel';
import EvidencePanel from '@/components/EvidencePanel';
import ConfidenceCard from '@/components/ConfidenceCard';
import ExecutionTrace from '@/components/ExecutionTrace';

export default function AnalysisPage() {
  const [hasImage, setHasImage] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisComplete, setAnalysisComplete] = useState(false);

  const handleAnalyze = () => {
    if (!hasImage) return;
    setIsAnalyzing(true);
    setAnalysisComplete(false);
    
    // Simulate backend agent processing time
    setTimeout(() => {
      setIsAnalyzing(false);
      setAnalysisComplete(true);
    }, 3000);
  };

  // Dummy GeoJSON evidence generated by the mock planner/agent
  const mockEvidenceLayers: MapLayerConfig[] = analysisComplete ? [
    {
      id: "detected-objects",
      type: "geojson",
      visible: true,
      data: {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [77.195, 28.615],
                  [77.220, 28.615],
                  [77.220, 28.630],
                  [77.195, 28.630],
                  [77.195, 28.615]
                ]
              ]
            }
          }
        ]
      }
    }
  ] : [];

  return (
    <div className="flex h-screen w-full bg-sat-bg-primary text-white overflow-hidden p-6 gap-6">
      
      {/* Left Column: Inputs & Status */}
      <aside className="w-[400px] flex flex-col gap-6 overflow-y-auto pr-2">
        <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-sat-accent flex justify-center items-center shadow-[0_0_15px_rgba(59,130,246,0.5)]">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2.5a2.5 2.5 0 0 0-2.5 2.5v14a2.5 2.5 0 0 0 5 0V5a2.5 2.5 0 0 0-2.5-2.5Z"/>
                </svg>
            </div>
            <h2 className="text-xl font-bold tracking-wider">SATQUERY AI</h2>
        </div>
        
        <ImageUploader onUpload={() => setHasImage(true)} uploaded={hasImage} />
        
        <QueryBox 
          onAnalyze={handleAnalyze} 
          disabled={!hasImage || isAnalyzing} 
          isAnalyzing={isAnalyzing}
        />
        
        {(isAnalyzing || analysisComplete) && <AnalysisStatus complete={analysisComplete} />}
        {analysisComplete && <ExecutionTrace />}
      </aside>

      {/* Center Column: Visual Evidence (Map/Image) */}
      <main className="flex-1 flex flex-col gap-4 relative">
        <div className="flex justify-between items-end">
            <h3 className="text-sm font-semibold text-gray-400 tracking-wider">VISUAL EVIDENCE</h3>
        </div>
        
        <div className="flex-1 w-full rounded-xl overflow-hidden border border-white/10 relative shadow-2xl">
           <MapViewer layers={mockEvidenceLayers} />
        </div>
        
        {analysisComplete && <EvidencePanel />}
      </main>

      {/* Right Column: Output & Insights */}
      <aside className="w-[400px] flex flex-col gap-6 overflow-y-auto pl-2">
        {analysisComplete ? (
          <>
            <ResultPanel />
            <ConfidenceCard />
          </>
        ) : (
          <div className="h-full flex flex-col items-center justify-center text-gray-500 border border-dashed border-gray-700 rounded-xl bg-black/20 p-8 text-center">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" className="mb-4 opacity-50">
                <circle cx="12" cy="12" r="10"/>
                <line x1="12" y1="8" x2="12" y2="12"/>
                <line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
            <p>Upload an image and ask a question to generate analysis.</p>
          </div>
        )}
      </aside>

    </div>
  );
}
